# Navigation links

main:
  - name: About
    url: /#about
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Publications
    url: /#publications
    weight: 30
  - name: Talks
    url: /#talks
    weight: 40
  - name: Projects
    url: /#projects
    weight: 50
  - name: Contact
    url: /#contact
    weight: 60
